/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimpleManualRouteImport } from './routes/simple.manual'
import { Route as EstimatorYieldRouteImport } from './routes/estimator_.yield'
import { Route as EstimatorWaterAllocationRouteImport } from './routes/estimator_.water-allocation'
import { Route as EstimatorResultsRouteImport } from './routes/estimator_.results'
import { Route as EstimatorIrrigationScheduleRouteImport } from './routes/estimator_.irrigation-schedule'
import { Route as EstimatorChartsRouteImport } from './routes/estimator_.charts'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleManualRoute = SimpleManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => SimpleRoute,
} as any)
const EstimatorYieldRoute = EstimatorYieldRouteImport.update({
  id: '/estimator_/yield',
  path: '/estimator/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorWaterAllocationRoute =
  EstimatorWaterAllocationRouteImport.update({
    id: '/estimator_/water-allocation',
    path: '/estimator/water-allocation',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstimatorResultsRoute = EstimatorResultsRouteImport.update({
  id: '/estimator_/results',
  path: '/estimator/results',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorIrrigationScheduleRoute =
  EstimatorIrrigationScheduleRouteImport.update({
    id: '/estimator_/irrigation-schedule',
    path: '/estimator/irrigation-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstimatorChartsRoute = EstimatorChartsRouteImport.update({
  id: '/estimator_/charts',
  path: '/estimator/charts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estimator': typeof EstimatorRoute
  '/fields': typeof FieldsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/simple': typeof SimpleRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/estimator/charts': typeof EstimatorChartsRoute
  '/estimator/irrigation-schedule': typeof EstimatorIrrigationScheduleRoute
  '/estimator/results': typeof EstimatorResultsRoute
  '/estimator/water-allocation': typeof EstimatorWaterAllocationRoute
  '/estimator/yield': typeof EstimatorYieldRoute
  '/simple/manual': typeof SimpleManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estimator': typeof EstimatorRoute
  '/fields': typeof FieldsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/simple': typeof SimpleRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/estimator/charts': typeof EstimatorChartsRoute
  '/estimator/irrigation-schedule': typeof EstimatorIrrigationScheduleRoute
  '/estimator/results': typeof EstimatorResultsRoute
  '/estimator/water-allocation': typeof EstimatorWaterAllocationRoute
  '/estimator/yield': typeof EstimatorYieldRoute
  '/simple/manual': typeof SimpleManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estimator': typeof EstimatorRoute
  '/fields': typeof FieldsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/simple': typeof SimpleRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/estimator_/charts': typeof EstimatorChartsRoute
  '/estimator_/irrigation-schedule': typeof EstimatorIrrigationScheduleRoute
  '/estimator_/results': typeof EstimatorResultsRoute
  '/estimator_/water-allocation': typeof EstimatorWaterAllocationRoute
  '/estimator_/yield': typeof EstimatorYieldRoute
  '/simple/manual': typeof SimpleManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/estimator'
    | '/fields'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/simple'
    | '/welcome'
    | '/estimator/charts'
    | '/estimator/irrigation-schedule'
    | '/estimator/results'
    | '/estimator/water-allocation'
    | '/estimator/yield'
    | '/simple/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/estimator'
    | '/fields'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/simple'
    | '/welcome'
    | '/estimator/charts'
    | '/estimator/irrigation-schedule'
    | '/estimator/results'
    | '/estimator/water-allocation'
    | '/estimator/yield'
    | '/simple/manual'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/estimator'
    | '/fields'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/simple'
    | '/welcome'
    | '/estimator_/charts'
    | '/estimator_/irrigation-schedule'
    | '/estimator_/results'
    | '/estimator_/water-allocation'
    | '/estimator_/yield'
    | '/simple/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EstimatorRoute: typeof EstimatorRoute
  FieldsRoute: typeof FieldsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SimpleRoute: typeof SimpleRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  EstimatorChartsRoute: typeof EstimatorChartsRoute
  EstimatorIrrigationScheduleRoute: typeof EstimatorIrrigationScheduleRoute
  EstimatorResultsRoute: typeof EstimatorResultsRoute
  EstimatorWaterAllocationRoute: typeof EstimatorWaterAllocationRoute
  EstimatorYieldRoute: typeof EstimatorYieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple/manual': {
      id: '/simple/manual'
      path: '/manual'
      fullPath: '/simple/manual'
      preLoaderRoute: typeof SimpleManualRouteImport
      parentRoute: typeof SimpleRoute
    }
    '/estimator_/yield': {
      id: '/estimator_/yield'
      path: '/estimator/yield'
      fullPath: '/estimator/yield'
      preLoaderRoute: typeof EstimatorYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator_/water-allocation': {
      id: '/estimator_/water-allocation'
      path: '/estimator/water-allocation'
      fullPath: '/estimator/water-allocation'
      preLoaderRoute: typeof EstimatorWaterAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator_/results': {
      id: '/estimator_/results'
      path: '/estimator/results'
      fullPath: '/estimator/results'
      preLoaderRoute: typeof EstimatorResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator_/irrigation-schedule': {
      id: '/estimator_/irrigation-schedule'
      path: '/estimator/irrigation-schedule'
      fullPath: '/estimator/irrigation-schedule'
      preLoaderRoute: typeof EstimatorIrrigationScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator_/charts': {
      id: '/estimator_/charts'
      path: '/estimator/charts'
      fullPath: '/estimator/charts'
      preLoaderRoute: typeof EstimatorChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SimpleRouteChildren {
  SimpleManualRoute: typeof SimpleManualRoute
}

const SimpleRouteChildren: SimpleRouteChildren = {
  SimpleManualRoute: SimpleManualRoute,
}

const SimpleRouteWithChildren =
  SimpleRoute._addFileChildren(SimpleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EstimatorRoute: EstimatorRoute,
  FieldsRoute: FieldsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SimpleRoute: SimpleRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  EstimatorChartsRoute: EstimatorChartsRoute,
  EstimatorIrrigationScheduleRoute: EstimatorIrrigationScheduleRoute,
  EstimatorResultsRoute: EstimatorResultsRoute,
  EstimatorWaterAllocationRoute: EstimatorWaterAllocationRoute,
  EstimatorYieldRoute: EstimatorYieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
